module.exports = [
  {
    "effect_changes":[

    ],
    "name":"chlorophyll",
    "generation":{
      "url":"http:\/\/pokeapi.co\/api\/v2\/generation\/3\/",
      "name":"generation-iii"
    },
    "pokemon":[
      {
        "slot":3,
        "is_hidden":true,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/1\/",
          "name":"bulbasaur"
        }
      },
      {
        "slot":3,
        "is_hidden":true,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/2\/",
          "name":"ivysaur"
        }
      },
      {
        "slot":3,
        "is_hidden":true,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/3\/",
          "name":"venusaur"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/43\/",
          "name":"oddish"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/44\/",
          "name":"gloom"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/45\/",
          "name":"vileplume"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/69\/",
          "name":"bellsprout"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/70\/",
          "name":"weepinbell"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/71\/",
          "name":"victreebel"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/102\/",
          "name":"exeggcute"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/103\/",
          "name":"exeggutor"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/114\/",
          "name":"tangela"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/182\/",
          "name":"bellossom"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/187\/",
          "name":"hoppip"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/188\/",
          "name":"skiploom"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/189\/",
          "name":"jumpluff"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/191\/",
          "name":"sunkern"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/192\/",
          "name":"sunflora"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/273\/",
          "name":"seedot"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/274\/",
          "name":"nuzleaf"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/275\/",
          "name":"shiftry"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/357\/",
          "name":"tropius"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/420\/",
          "name":"cherubi"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/465\/",
          "name":"tangrowth"
        }
      },
      {
        "slot":3,
        "is_hidden":true,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/470\/",
          "name":"leafeon"
        }
      },
      {
        "slot":2,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/540\/",
          "name":"sewaddle"
        }
      },
      {
        "slot":2,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/541\/",
          "name":"swadloon"
        }
      },
      {
        "slot":2,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/542\/",
          "name":"leavanny"
        }
      },
      {
        "slot":3,
        "is_hidden":true,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/546\/",
          "name":"cottonee"
        }
      },
      {
        "slot":3,
        "is_hidden":true,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/547\/",
          "name":"whimsicott"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/548\/",
          "name":"petilil"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/549\/",
          "name":"lilligant"
        }
      },
      {
        "slot":2,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/556\/",
          "name":"maractus"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/585\/",
          "name":"deerling"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/586\/",
          "name":"sawsbuck"
        }
      }
    ],
    "is_main_series":true,
    "effect_entries":[
      {
        "short_effect":"Doubles Speed during strong sunlight.",
        "effect":"This Pok\u00e9mon's Speed is doubled during strong sunlight.\n\nThis bonus does not count as a stat modifier.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/9\/",
          "name":"en"
        }
      }
    ],
    "names":[
      {
        "name":"Chlorophyll",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/9\/",
          "name":"en"
        }
      },
      {
        "name":"Clorofilla",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/8\/",
          "name":"it"
        }
      },
      {
        "name":"Clorofila",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/7\/",
          "name":"es"
        }
      },
      {
        "name":"Chlorophyll",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/6\/",
          "name":"de"
        }
      },
      {
        "name":"Chlorophylle",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/5\/",
          "name":"fr"
        }
      },
      {
        "name":"\uc5fd\ub85d\uc18c",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/3\/",
          "name":"ko"
        }
      },
      {
        "name":"\u3088\u3046\u308a\u3087\u304f\u305d",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/1\/",
          "name":"ja"
        }
      }
    ],
    "flavor_text_entries":[
      {
        "flavor_text":"\u6674\u308c\u306e\u3068\u304d\u3000\u7d20\u65e9\u3055\u304c\n\u3042\u304c\u308b\u3002",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/11\/",
          "name":"ja-kanji"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/16\/",
          "name":"omega-ruby-alpha-sapphire"
        }
      },
      {
        "flavor_text":"Boosts the Pok\u00e9mon\u2019s\nSpeed stat in sunshine.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/9\/",
          "name":"en"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/16\/",
          "name":"omega-ruby-alpha-sapphire"
        }
      },
      {
        "flavor_text":"Se c\u2019\u00e8 il sole, la statistica\nVelocit\u00e0 aumenta.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/8\/",
          "name":"it"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/16\/",
          "name":"omega-ruby-alpha-sapphire"
        }
      },
      {
        "flavor_text":"Sube la Velocidad cuando hay\nsol.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/7\/",
          "name":"es"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/16\/",
          "name":"omega-ruby-alpha-sapphire"
        }
      },
      {
        "flavor_text":"Steigert bei Sonnenschein\ndie Initiative.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/6\/",
          "name":"de"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/16\/",
          "name":"omega-ruby-alpha-sapphire"
        }
      },
      {
        "flavor_text":"Augmente la Vitesse du\nPok\u00e9mon s\u2019il y a du soleil.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/5\/",
          "name":"fr"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/16\/",
          "name":"omega-ruby-alpha-sapphire"
        }
      },
      {
        "flavor_text":"\ub9d1\uc744 \ub54c \uc2a4\ud53c\ub4dc\uac00\n\uc62c\ub77c\uac04\ub2e4.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/3\/",
          "name":"ko"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/16\/",
          "name":"omega-ruby-alpha-sapphire"
        }
      },
      {
        "flavor_text":"\u306f\u308c\u306e\u3068\u304d\u3000\u3059\u3070\u3084\u3055\u304c\n\u3042\u304c\u308b\u3002",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/1\/",
          "name":"ja"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/16\/",
          "name":"omega-ruby-alpha-sapphire"
        }
      },
      {
        "flavor_text":"\u6674\u308c\u306e\u3068\u304d\u3000\u7d20\u65e9\u3055\u304c\n\u3042\u304c\u308b\u3002",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/11\/",
          "name":"ja-kanji"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/15\/",
          "name":"x-y"
        }
      },
      {
        "flavor_text":"Boosts the Pok\u00e9mon\u2019s\nSpeed stat in sunshine.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/9\/",
          "name":"en"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/15\/",
          "name":"x-y"
        }
      },
      {
        "flavor_text":"Se c\u2019\u00e8 il sole, la statistica\nVelocit\u00e0 aumenta.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/8\/",
          "name":"it"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/15\/",
          "name":"x-y"
        }
      },
      {
        "flavor_text":"Sube la Velocidad cuando hay\nsol.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/7\/",
          "name":"es"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/15\/",
          "name":"x-y"
        }
      },
      {
        "flavor_text":"Steigert bei Sonnenschein\ndie Initiative.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/6\/",
          "name":"de"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/15\/",
          "name":"x-y"
        }
      },
      {
        "flavor_text":"Augmente la Vitesse du\nPok\u00e9mon s\u2019il y a du soleil.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/5\/",
          "name":"fr"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/15\/",
          "name":"x-y"
        }
      },
      {
        "flavor_text":"\ub9d1\uc744 \ub54c \uc2a4\ud53c\ub4dc\uac00\n\uc62c\ub77c\uac04\ub2e4.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/3\/",
          "name":"ko"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/15\/",
          "name":"x-y"
        }
      },
      {
        "flavor_text":"\u306f\u308c\u306e\u3068\u304d\u3000\u3059\u3070\u3084\u3055\u304c\n\u3042\u304c\u308b\u3002",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/1\/",
          "name":"ja"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/15\/",
          "name":"x-y"
        }
      },
      {
        "flavor_text":"Boosts the Pok\u00e9mon\u2019s\nSpeed in sunshine.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/9\/",
          "name":"en"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/14\/",
          "name":"black-2-white-2"
        }
      },
      {
        "flavor_text":"Boosts the Pok\u00e9mon\u2019s\nSpeed in sunshine.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/9\/",
          "name":"en"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/11\/",
          "name":"black-white"
        }
      },
      {
        "flavor_text":"Augmente la Vitesse du\nPok\u00e9mon s\u2019il y a du soleil.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/5\/",
          "name":"fr"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/11\/",
          "name":"black-white"
        }
      },
      {
        "flavor_text":"Boosts the Pok\u00e9mon\u2019s\nSpeed in sunshine.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/9\/",
          "name":"en"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/10\/",
          "name":"heartgold-soulsilver"
        }
      },
      {
        "flavor_text":"Boosts the Pok\u00e9mon\u2019s\nSpeed in sunshine.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/9\/",
          "name":"en"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/9\/",
          "name":"platinum"
        }
      },
      {
        "flavor_text":"Boosts the Pok\u00e9mon\u2019s\nSpeed in sunshine.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/9\/",
          "name":"en"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/8\/",
          "name":"diamond-pearl"
        }
      },
      {
        "flavor_text":"Raises SPEED in sunshine.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/9\/",
          "name":"en"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/7\/",
          "name":"firered-leafgreen"
        }
      },
      {
        "flavor_text":"Raises SPEED in sunshine.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/9\/",
          "name":"en"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/6\/",
          "name":"emerald"
        }
      },
      {
        "flavor_text":"Raises SPEED in sunshine.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/9\/",
          "name":"en"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/5\/",
          "name":"ruby-sapphire"
        }
      }
    ],
    "id":34
  },
  {
    "effect_changes":[

    ],
    "name":"overgrow",
    "generation":{
      "url":"http:\/\/pokeapi.co\/api\/v2\/generation\/3\/",
      "name":"generation-iii"
    },
    "pokemon":[
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/1\/",
          "name":"bulbasaur"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/2\/",
          "name":"ivysaur"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/3\/",
          "name":"venusaur"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/152\/",
          "name":"chikorita"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/153\/",
          "name":"bayleef"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/154\/",
          "name":"meganium"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/252\/",
          "name":"treecko"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/253\/",
          "name":"grovyle"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/254\/",
          "name":"sceptile"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/387\/",
          "name":"turtwig"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/388\/",
          "name":"grotle"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/389\/",
          "name":"torterra"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/495\/",
          "name":"snivy"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/496\/",
          "name":"servine"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/497\/",
          "name":"serperior"
        }
      },
      {
        "slot":3,
        "is_hidden":true,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/511\/",
          "name":"pansage"
        }
      },
      {
        "slot":3,
        "is_hidden":true,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/512\/",
          "name":"simisage"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/650\/",
          "name":"chespin"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/651\/",
          "name":"quilladin"
        }
      },
      {
        "slot":1,
        "is_hidden":false,
        "pokemon":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/pokemon\/652\/",
          "name":"chesnaught"
        }
      }
    ],
    "is_main_series":true,
    "effect_entries":[
      {
        "short_effect":"Strengthens grass moves to inflict 1.5\u00d7 damage at 1\/3 max HP or less.",
        "effect":"When this Pok\u00e9mon has 1\/3 or less of its HP remaining, its grass-type moves inflict 1.5\u00d7 as much regular damage.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/9\/",
          "name":"en"
        }
      }
    ],
    "names":[
      {
        "name":"Overgrow",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/9\/",
          "name":"en"
        }
      },
      {
        "name":"Erbaiuto",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/8\/",
          "name":"it"
        }
      },
      {
        "name":"Espesura",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/7\/",
          "name":"es"
        }
      },
      {
        "name":"Notd\u00fcnger",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/6\/",
          "name":"de"
        }
      },
      {
        "name":"Engrais",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/5\/",
          "name":"fr"
        }
      },
      {
        "name":"\uc2ec\ub85d",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/3\/",
          "name":"ko"
        }
      },
      {
        "name":"\u3057\u3093\u308a\u3087\u304f",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/1\/",
          "name":"ja"
        }
      }
    ],
    "flavor_text_entries":[
      {
        "flavor_text":"\u30d4\u30f3\u30c1\u306e\u3068\u304d\u3000\u304f\u3055\u306e\n\u5a01\u529b\u304c\u3000\u3042\u304c\u308b\u3002",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/11\/",
          "name":"ja-kanji"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/16\/",
          "name":"omega-ruby-alpha-sapphire"
        }
      },
      {
        "flavor_text":"Powers up Grass-type moves\nwhen the Pok\u00e9mon is in trouble.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/9\/",
          "name":"en"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/16\/",
          "name":"omega-ruby-alpha-sapphire"
        }
      },
      {
        "flavor_text":"Quando si \u00e8 in difficolt\u00e0, potenzia  \nle mosse di tipo Erba.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/8\/",
          "name":"it"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/16\/",
          "name":"omega-ruby-alpha-sapphire"
        }
      },
      {
        "flavor_text":"Potencia los ataques de tipo\nPlanta en un apuro.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/7\/",
          "name":"es"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/16\/",
          "name":"omega-ruby-alpha-sapphire"
        }
      },
      {
        "flavor_text":"Erh\u00f6ht in Notf\u00e4llen die St\u00e4rke\nvon Pflanzen-Attacken.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/6\/",
          "name":"de"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/16\/",
          "name":"omega-ruby-alpha-sapphire"
        }
      },
      {
        "flavor_text":"Booste les capacit\u00e9s Plante en\ncas de besoin.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/5\/",
          "name":"fr"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/16\/",
          "name":"omega-ruby-alpha-sapphire"
        }
      },
      {
        "flavor_text":"\uc704\uae09\ud560 \ub54c \ud480\ud0c0\uc785\uc758\n\uc704\ub825\uc774 \uc62c\ub77c\uac04\ub2e4.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/3\/",
          "name":"ko"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/16\/",
          "name":"omega-ruby-alpha-sapphire"
        }
      },
      {
        "flavor_text":"\u30d4\u30f3\u30c1\u306e\u3068\u304d\u3000\u304f\u3055\u306e\n\u3044\u308a\u3087\u304f\u304c\u3000\u3042\u304c\u308b\u3002",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/1\/",
          "name":"ja"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/16\/",
          "name":"omega-ruby-alpha-sapphire"
        }
      },
      {
        "flavor_text":"\u30d4\u30f3\u30c1\u306e\u3068\u304d\u3000\u304f\u3055\u306e\n\u5a01\u529b\u304c\u3000\u3042\u304c\u308b\u3002",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/11\/",
          "name":"ja-kanji"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/15\/",
          "name":"x-y"
        }
      },
      {
        "flavor_text":"Powers up Grass-type moves\nwhen the Pok\u00e9mon is in trouble.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/9\/",
          "name":"en"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/15\/",
          "name":"x-y"
        }
      },
      {
        "flavor_text":"Quando si \u00e8 in difficolt\u00e0, potenzia\nle mosse di tipo Erba.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/8\/",
          "name":"it"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/15\/",
          "name":"x-y"
        }
      },
      {
        "flavor_text":"Potencia los ataques de tipo\nPlanta en un apuro.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/7\/",
          "name":"es"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/15\/",
          "name":"x-y"
        }
      },
      {
        "flavor_text":"Erh\u00f6ht in Notf\u00e4llen die St\u00e4rke\nvon Pflanzen-Attacken.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/6\/",
          "name":"de"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/15\/",
          "name":"x-y"
        }
      },
      {
        "flavor_text":"Booste les capacit\u00e9s Plante en\ncas de besoin.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/5\/",
          "name":"fr"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/15\/",
          "name":"x-y"
        }
      },
      {
        "flavor_text":"\uc704\uae09\ud560 \ub54c \ud480\ud0c0\uc785\uc758\n\uc704\ub825\uc774 \uc62c\ub77c\uac04\ub2e4.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/3\/",
          "name":"ko"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/15\/",
          "name":"x-y"
        }
      },
      {
        "flavor_text":"\u30d4\u30f3\u30c1\u306e\u3068\u304d\u3000\u304f\u3055\u306e\n\u3044\u308a\u3087\u304f\u304c\u3000\u3042\u304c\u308b\u3002",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/1\/",
          "name":"ja"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/15\/",
          "name":"x-y"
        }
      },
      {
        "flavor_text":"Powers up Grass-type\nmoves in a pinch.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/9\/",
          "name":"en"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/14\/",
          "name":"black-2-white-2"
        }
      },
      {
        "flavor_text":"Powers up Grass-type\nmoves in a pinch.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/9\/",
          "name":"en"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/11\/",
          "name":"black-white"
        }
      },
      {
        "flavor_text":"Booste les capacit\u00e9s\nPlante en cas de besoin.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/5\/",
          "name":"fr"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/11\/",
          "name":"black-white"
        }
      },
      {
        "flavor_text":"Powers up Grass-type\nmoves in a pinch.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/9\/",
          "name":"en"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/10\/",
          "name":"heartgold-soulsilver"
        }
      },
      {
        "flavor_text":"Powers up Grass-type\nmoves in a pinch.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/9\/",
          "name":"en"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/9\/",
          "name":"platinum"
        }
      },
      {
        "flavor_text":"Powers up Grass-type\nmoves in a pinch.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/9\/",
          "name":"en"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/8\/",
          "name":"diamond-pearl"
        }
      },
      {
        "flavor_text":"Ups GRASS moves in a pinch.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/9\/",
          "name":"en"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/7\/",
          "name":"firered-leafgreen"
        }
      },
      {
        "flavor_text":"Ups GRASS moves in a pinch.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/9\/",
          "name":"en"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/6\/",
          "name":"emerald"
        }
      },
      {
        "flavor_text":"Ups GRASS moves in a pinch.",
        "language":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/language\/9\/",
          "name":"en"
        },
        "version_group":{
          "url":"http:\/\/pokeapi.co\/api\/v2\/version-group\/5\/",
          "name":"ruby-sapphire"
        }
      }
    ],
    "id":65
  }
]
